baseurl = "https://1ambda.github.io/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "Old Lisper"
canonifyurls = true
theme = "hugo-theme-learn"
googleAnalytics = "UA-52181619-1"
disqusShortname = "1ambda"
languageCode = "en-us"

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "1ambda"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  editURL = "https://github.com/1ambda/1ambda.github.io-hugo/edit/master/content/"
  description = "hugo content for 1ambda.github.io"
  author = "1ambda"